# Generated by Django 2.1.5 on 2020-06-24 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_item_todolist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='todolist',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
